{
  gInterpreter->AddIncludePath("/home/henrique/Documents/SoLAr/WVFAnaSoLAr/class/");
  gInterpreter->AddIncludePath("/home/henrique/Dropbox/APC_Paris/Root/cold_box_analysis/class/");
  gStyle->SetPadTickX(1);
  gStyle->SetPadTickY(1);
  gStyle->SetPadGridX(1);
  gStyle->SetPadGridY(1);
  gStyle->SetOptFit(111);
  gStyle->SetLineScalePS(1)
}
